--------------------------------------------------------
--  File created - Tuesday-December-04-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LATA_LOGIN
--------------------------------------------------------

  CREATE TABLE "HR"."LATA_LOGIN" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"USERTYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007015" ON "HR"."LATA_LOGIN" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LATA_LOGIN
--------------------------------------------------------

  ALTER TABLE "HR"."LATA_LOGIN" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."LATA_LOGIN" MODIFY ("USERTYPE" NOT NULL ENABLE);
  ALTER TABLE "HR"."LATA_LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HR"."LATA_LOGIN" MODIFY ("USER_ID" NOT NULL ENABLE);
